/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package design.patterns;

import design.patterns.builder_design.AbstractSmartphone;
import design.patterns.builder_design.SmartphoneBuilder;

public class App {

    public static void main(String[] args) {
        
        //Builder Design Pattern
        System.out.println("Customer: I need a Samsung phone");
        AbstractSmartphone smartphone1 = new SmartphoneBuilder()
            .setCamera(50)
            .setCpu("Snapdragon 695")
            .setDisplaySize(6.1f)
            .setRam(8)
            .setStorage(128)
            .setName("S22")
            .getSmartphone("Samsung");
            System.out.println(smartphone1.makeCall("98123213"));

        System.out.println("Customer: I need an iPhone");
        AbstractSmartphone smartphone2 = new SmartphoneBuilder()
            .setCamera(48)
            .setCpu("A16 Bionic")
            .setDisplaySize(6.1f)
            .setRam(6)
            .setStorage(128)
            .setName("14 pro")
            .getSmartphone("iPhone");
            System.out.println(smartphone2.sendSMS("98123213", "Hi"));
    }
}
